import {
  adoptCat,
  ADOPT_CAT_FAILURE,
  ADOPT_CAT_REQUEST,
  ADOPT_CAT_SUCCESS,
  fetchCat,
  FETCH_CAT_FAILURE,
  FETCH_CAT_REQUEST,
  FETCH_CAT_SUCCESS,
} from './cat';

import {
  adoptDog,
  ADOPT_DOG_FAILURE,
  ADOPT_DOG_REQUEST,
  ADOPT_DOG_SUCCESS,
  fetchDog,
  FETCH_DOG_FAILURE,
  FETCH_DOG_REQUEST,
  FETCH_DOG_SUCCESS,
} from './dog';

export {
  adoptCat,
  ADOPT_CAT_FAILURE,
  ADOPT_CAT_REQUEST,
  ADOPT_CAT_SUCCESS,
  fetchCat,
  FETCH_CAT_FAILURE,
  FETCH_CAT_REQUEST,
  FETCH_CAT_SUCCESS,
  adoptDog,
  ADOPT_DOG_FAILURE,
  ADOPT_DOG_REQUEST,
  ADOPT_DOG_SUCCESS,
  fetchDog,
  FETCH_DOG_FAILURE,
  FETCH_DOG_REQUEST,
  FETCH_DOG_SUCCESS,
};
